[tox]
requires =
    tox-uv>=1
skipsdist = true
skip_missing_interpreters = true
envlist =
    py{311,312,313,314,315},
    ruff,
    bandit,
    readme

[gh-actions]
python =
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314
    3.15: py315

[testenv]
envdir = {toxworkdir}/venv/{envname}
setenv =
    PYTHONDONTWRITEBYTECODE=1
    PYTHONWARNINGS=once
basepython =
    py311: python3.11
    py312: python3.12
    py313: python3.13
    py314: python3.14
    py315: python3.15
deps =
    .
commands =
    uv pip list
    sphinx-build -b html -d _build/doctree docs _build/html

[testenv:ruff]
skip_install = true
basepython = python3
deps =
    ruff
commands =
    ruff check src
    ruff format --check src

[testenv:bandit]
skip_install = true
basepython = python3
deps = bandit
commands = bandit --quiet -r src docs

[testenv:readme]
skip_install = true
basepython = python3
deps =
    twine>=1.12.0
commands =
    uv build
    twine check dist/*
